// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gulljxrocpzahgwyfvgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1bGxqeHJvY3B6YWhnd3lmdmdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NTQ1MDEsImV4cCI6MjA3NDIzMDUwMX0.PqU2KTdDZwsb7Ix-ymiebPBJR4M2QC4iEDwwNgGE_YE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});